### ISSUE TITLE
Gas optmization

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#10]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L39

I think you may try to use uint256 and see if some gas is saved. Solidity has some tricks inside of it. I am not sure if it will help you and will try later.

And you may try to use this toll to help you visualize how much gas are you spending.

https://github.com/cgewecke/eth-gas-reporter

**Comment by stefek99** [comment]
> try to use uint256

`uint` and `uint256` are the same: https://ethereum.stackexchange.com/questions/43241/why-write-uint256-instead-of-uint-if-theyre-the-same-thing

I know that `structs` can align `uint32` and `uint16` to save gas, here it doesn't matter?

**Comment by fosgate29** [comment]
Right. ``uint`` and ``uint256`` are the same. Will try to see if there is some point to save gas in the contract
