### ISSUE TITLE
Avoid fallback function

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#3]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L48

I don´t see any reason for you to use fallback function. Create a function called contribute(), for example.

Fallback should be used in a very specific situation and it is Vitalik saying, not me. https://www.reddit.com/r/ethereum/comments/47ts9p/is_it_unsafe_to_send_eth_from_contracts_with_the/d0fperf/
>"establishing as a convention that fallback functions should generally not be used except in very specific cases."

**Comment by stefek99** [comment]
But how would people send `ETH` if there is no fallback function?

Assuming regular users, not those who know how to write to the smart contract directly...

**Comment by fosgate29** [comment]
I undestand your point. In that case, it is ok to use fallback.
