### ISSUE TITLE
Unnecessary code/logic

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#4]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L50

You are adding logic to your code that should be avoided. Code must be simple as possible, to avoid any problems. More code, more problems. 

If msg.value == 0, revert. 

My suggested code
```
require(msg.value > 0);
```

**Comment by stefek99** [comment]
Nope.

Send `0` to withdraw.

Some people do not know how to call functions.

Offering them easy way to withdraw, by sending `0`.
