### ISSUE TITLE
Best practice: Lock pragmas to specific compiler version

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#5]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L1

https://consensys.github.io/smart-contract-best-practices/recommendations/#lock-pragmas-to-specific-compiler-version

>Contracts should be deployed with the same compiler version and flags that they have been tested the most with. Locking the pragma helps ensure that contracts do not accidentally get deployed using, for example, the latest compiler which may have higher risks of undiscovered bugs. Contracts may also be deployed by others and the pragma indicates the compiler version intended by the original authors.

**Comment by stefek99** [comment]
Why are so many people using ` ^0.4.23` then?

Weird... Minor. Let it flow...

**Comment by fosgate29** [comment]
It is a best practice. Just like identation, name of functions, etc.
