### ISSUE TITLE
Use SafeMath

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#6]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L67

It has a low probability of attack, but you must use SafeMath practice to avoid an overflow. If price is a high value, it can overflow or underflow here.

You can use OpenZeppelin SafeMath library: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol

Or you can add the SafeMath in your contract if you don´t want to add too much code in your contract.

**Comment by stefek99** [comment]
Is there are any value that could trigger underflow / overflow? 

Or is SafeMath "just in case"?

**Comment by fosgate29** [comment]
"Just in case". And if someone is auditing your code and see that you are using SafeMath or any logic to avoid overflow/underflow, it saves time because he don´t have to worry about overflow/underflow maths. It is a best practice.
