### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#7]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L88

I would remove this block from the finalize() function. If this loops is broke, you won´t be able to finalize the auction. It uses loops, so it may have a gas problem and you get locked.

I would do this:
```
function refundContributors() ended() onlyOwner(){
    for (uint i = 0; i < accountsList.length;  i++) {
      if (bids[accountsList[i]] > 0) {
       ......
      }
    } 
} 
```

And if you want to get extra cautions to avoid out of gas (if you have one million of contributors, you won´t be able to execute this loop), you may add blocks of refunds to avoid out of gas. but since user can call refund(), you are safe. user can go and get his funds back

**Comment by stefek99** [comment]
Good thinking.

I was aware of loops beyond gas limit: https://github.com/kleros/openiico-contract/issues/26

Thanks so much for the comments!
