### ISSUE TITLE
Reentrancy attack

### ISSUE THREAD

**Issue by fosgate29** [astralship/eos#8]
https://github.com/astralship/eos/blob/1359e14e0319c6019eb9c7e57348b95c722e3dd6/contracts/Auction.sol#L90

You set to zero binder value in the next line, but to avoid reentrancy attack, you have to zero it first, before using send or transfer.

And you should avoid send. Use transfer. It will revert and is limit to 2300 gas. It will help you keep safe.

My suggestion:

```
        uint refundValue = bids[accountsList[i]];
        bids[accountsList[i]] = 0;
        accountsList[i].send(refundValue); 
```` 

Also, emit an event after the refund. It is cheap and will help you track your refunds.

**Comment by stefek99** [comment]
WOW.

Setting to zero first.

Best techniques...

I’ll redeploy and update the contract, thank you for that!!!
